<?php
$static_colors = array(
	's1' => array(
		'ID' => 's1',
		'label' => 'Orquídea Chumbo 91',
		'thumbnail' => Piki::url( 'images/colors/1.jpg', __FILE__ ),
	),
	's2' => array(
		'ID' => 's2',
		'label' => 'Orquídea Lavanda 34',
		'thumbnail' => Piki::url( 'images/colors/2.jpg', __FILE__ ),
	),
	's3' => array(
		'ID' => 's3',
		'label' => 'Romântica Bege Rosado 55',
		'thumbnail' => Piki::url( 'images/colors/3.jpg', __FILE__ ),
	),
	's4' => array(
		'ID' => 's4',
		'label' => 'Romântica Rosa Seco 47',
		'thumbnail' => Piki::url( 'images/colors/4.jpg', __FILE__ ),
	),
	's5' => array(
		'ID' => 's5',
		'label' => 'Romântica Branco 20',
		'thumbnail' => Piki::url( 'images/colors/5.jpg', __FILE__ ),
	),
	's6' => array(
		'ID' => 's6',
		'label' => 'Caríbdis Branco 20',
		'thumbnail' => Piki::url( 'images/colors/6.jpg', __FILE__ ),
	),
	's7' => array(
		'ID' => 's7',
		'label' => 'Oncinha Preto 27',
		'thumbnail' => Piki::url( 'images/colors/7.jpg', __FILE__ ),
	),
	's8' => array(
		'ID' => 's8',
		'label' => 'Habella Rosa Glacê 31',
		'thumbnail' => Piki::url( 'images/colors/8.jpg', __FILE__ ),
	),
	's9' => array(
		'ID' => 's9',
		'label' => 'Vivace Champanhe 59',
		'thumbnail' => Piki::url( 'images/colors/9.jpg', __FILE__ ),
	),
	's10' => array(
		'ID' => 's10',
		'label' => 'Joli Carmim 05',
		'thumbnail' => Piki::url( 'images/colors/10.jpg', __FILE__ ),
	),
	's11' => array(
		'ID' => 's11',
		'label' => 'New Romance Branco 20',
		'thumbnail' => Piki::url( 'images/colors/11.jpg', __FILE__ ),
	),
	's12' => array(
		'ID' => 's12',
		'label' => 'Fofita Branco 20',
		'thumbnail' => Piki::url( 'images/colors/12.jpg', __FILE__ ),
	),
	's13' => array(
		'ID' => 's13',
		'label' => 'Qatar Coral 42',
		'thumbnail' => Piki::url( 'images/colors/13.jpg', __FILE__ ),
	),
	's14' => array(
		'ID' => 's14',
		'label' => 'Astral Azul Marinho 16',
		'thumbnail' => Piki::url( 'images/colors/14.jpg', __FILE__ ),
	),
	's15' => array(
		'ID' => 's15',
		'label' => 'Guinee Bordô 24',
		'thumbnail' => Piki::url( 'images/colors/15.jpg', __FILE__ ),
	),
	's16' => array(
		'ID' => 's16',
		'label' => 'Galler Branco 20',
		'thumbnail' => Piki::url( 'images/colors/16.jpg', __FILE__ ),
	),
	's17' => array(
		'ID' => 's17',
		'label' => 'Alborg Goiaba 36',
		'thumbnail' => Piki::url( 'images/colors/17.jpg', __FILE__ ),
	),
	's18' => array(
		'ID' => 's18',
		'label' => 'Topázio Capuccino 40',
		'thumbnail' => Piki::url( 'images/colors/18.jpg', __FILE__ ),
	),
	's19' => array(
		'ID' => 's19',
		'label' => 'Titânia Preto 27',
		'thumbnail' => Piki::url( 'images/colors/19.jpg', __FILE__ ),
	),
	's20' => array(
		'ID' => 's20',
		'label' => 'Nuvem Champanhe 59',
		'thumbnail' => Piki::url( 'images/colors/20.jpg', __FILE__ ),
	),
	's21' => array(
		'ID' => 's21',
		'label' => 'Carence Rosa Gerânio 02',
		'thumbnail' => Piki::url( 'images/colors/21.jpg', __FILE__ ),
	),
	's22' => array(
		'ID' => 's22',
		'label' => 'Infantil Verde Cerrado 45',
		'thumbnail' => Piki::url( 'images/colors/22.jpg', __FILE__ ),
	),
	's23' => array(
		'ID' => 's23',
		'label' => 'Infantil Docinhos Pink 51',
		'thumbnail' => Piki::url( 'images/colors/23.jpg', __FILE__ ),
	),
	's24' => array(
		'ID' => 's24',
		'label' => 'Infantil Azul Capri 1',
		'thumbnail' => Piki::url( 'images/colors/24.jpg', __FILE__ ),
	),
	's25' => array(
		'ID' => 's25',
		'label' => 'Infantil Marinho 15',
		'thumbnail' => Piki::url( 'images/colors/25.jpg', __FILE__ ),
	),
	's26' => array(
		'ID' => 's26',
		'label' => 'Infantil Laranja 84',
		'thumbnail' => Piki::url( 'images/colors/26.jpg', __FILE__ ),
	),
	's27' => array(
		'ID' => 's27',
		'label' => 'Infantil Uva 82',
		'thumbnail' => Piki::url( 'images/colors/27.jpg', __FILE__ ),
	),
	's28' => array(
		'ID' => 's28',
		'label' => 'Infantil Azul Caribe 07',
		'thumbnail' => Piki::url( 'images/colors/28.jpg', __FILE__ ),
	),
	's29' => array(
		'ID' => 's29',
		'label' => 'Infantil Coral 42',
		'thumbnail' => Piki::url( 'images/colors/29.jpg', __FILE__ ),
	),
	's30' => array(
		'ID' => 's30',
		'label' => 'Infantil Grafite 85',
		'thumbnail' => Piki::url( 'images/colors/30.jpg', __FILE__ ),
	),
	's31' => array(
		'ID' => 's31',
		'label' => 'Infantil Pink 51',
		'thumbnail' => Piki::url( 'images/colors/31.jpg', __FILE__ ),
	),
	's32' => array(
		'ID' => 's32',
		'label' => 'Infantil Branco 20',
		'thumbnail' => Piki::url( 'images/colors/32.jpg', __FILE__ ),
	),
	's33' => array(
		'ID' => 's33',
		'label' => 'Infantil Amarelo Solar 77',
		'thumbnail' => Piki::url( 'images/colors/33.jpg', __FILE__ ),
	),
	's34' => array(
		'ID' => 's34',
		'label' => 'Infantil Azul Capri 1',
		'thumbnail' => Piki::url( 'images/colors/34.jpg', __FILE__ ),
	),
	's35' => array(
		'ID' => 's35',
		'label' => 'Infantil Uva 82',
		'thumbnail' => Piki::url( 'images/colors/35.jpg', __FILE__ ),
	),
	's36' => array(
		'ID' => 's36',
		'label' => 'Infantil Violeta 51',
		'thumbnail' => Piki::url( 'images/colors/36.jpg', __FILE__ ),
	),
	's37' => array(
		'ID' => 's37',
		'label' => 'Infantil Branco 20',
		'thumbnail' => Piki::url( 'images/colors/37.jpg', __FILE__ ),
	),
	's38' => array(
		'ID' => 's38',
		'label' => 'Infantil Branco 20',
		'thumbnail' => Piki::url( 'images/colors/38.jpg', __FILE__ ),
	),
	's39' => array(
		'ID' => 's39',
		'label' => 'Celta Branco 20',
		'thumbnail' => Piki::url( 'images/colors/39.jpg', __FILE__ ),
	),
	's40' => array(
		'ID' => 's40',
		'label' => 'Corujinha Branco 20',
		'thumbnail' => Piki::url( 'images/colors/40.jpg', __FILE__ ),
	),
	's41' => array(
		'ID' => 's41',
		'label' => 'Bermudoll Girl Branco 20',
		'thumbnail' => Piki::url( 'images/colors/41.jpg', __FILE__ ),
	),
	's42' => array(
		'ID' => 's42',
		'label' => 'Calcinha Infantil Maçãs Amarelo Verano',
		'thumbnail' => Piki::url( 'images/colors/42.jpg', __FILE__ ),
	),
	's43' => array(
		'ID' => 's43',
		'label' => 'Cerejas Laranja 84',
		'thumbnail' => Piki::url( 'images/colors/43.jpg', __FILE__ ),
	),
	's44' => array(
		'ID' => 's44',
		'label' => 'Venti Anni Violeta 81',
		'thumbnail' => Piki::url( 'images/colors/44.jpg', __FILE__ ),
	),
	's45' => array(
		'ID' => 's45',
		'label' => 'Argent Preto 27',
		'thumbnail' => Piki::url( 'images/colors/45.jpg', __FILE__ ),
	),
	's46' => array(
		'ID' => 's46',
		'label' => 'Canção Branco 20',
		'thumbnail' => Piki::url( 'images/colors/46.jpg', __FILE__ ),
	),
	's47' => array(
		'ID' => 's47',
		'label' => 'Noite Algodão Onça 71',
		'thumbnail' => Piki::url( 'images/colors/47.jpg', __FILE__ ),
	),
	's48' => array(
		'ID' => 's48',
		'label' => 'Brigitte Onça 71',
		'thumbnail' => Piki::url( 'images/colors/48.jpg', __FILE__ ),
	),
	's49' => array(
		'ID' => 's49',
		'label' => 'Brigitte Champanhe 59',
		'thumbnail' => Piki::url( 'images/colors/49.jpg', __FILE__ ),
	),
	's50' => array(
		'ID' => 's50',
		'label' => 'Biscuit Champanhe 59',
		'thumbnail' => Piki::url( 'images/colors/50.jpg', __FILE__ ),
	),
	's51' => array(
		'ID' => 's51',
		'label' => 'DM Barra Verde Laguna 89',
		'thumbnail' => Piki::url( 'images/colors/51.jpg', __FILE__ ),
	),
	's52' => array(
		'ID' => 's52',
		'label' => 'DM Barra Goiaba 36',
		'thumbnail' => Piki::url( 'images/colors/52.jpg', __FILE__ ),
	),
	's53' => array(
		'ID' => 's53',
		'label' => 'Noite e Carícia Grafite 85',
		'thumbnail' => Piki::url( 'images/colors/53.jpg', __FILE__ ),
	),
	's54' => array(
		'ID' => 's54',
		'label' => 'Xamego Rosa Glacê 31',
		'thumbnail' => Piki::url( 'images/colors/54.jpg', __FILE__ ),
	),
	's55' => array(
		'ID' => 's55',
		'label' => 'Antuerpia Lavanda 34',
		'thumbnail' => Piki::url( 'images/colors/55.jpg', __FILE__ ),
	),
	's56' => array(
		'ID' => 's56',
		'label' => 'Brilho Preto 27',
		'thumbnail' => Piki::url( 'images/colors/56.jpg', __FILE__ ),
	),
	's57' => array(
		'ID' => 's57',
		'label' => 'Purisma Branco 20',
		'thumbnail' => Piki::url( 'images/colors/57.jpg', __FILE__ ),
	),
	's58' => array(
		'ID' => 's58',
		'label' => 'Videnza Branco 20',
		'thumbnail' => Piki::url( 'images/colors/58.jpg', __FILE__ ),
	),
	's59' => array(
		'ID' => 's59',
		'label' => 'Zebrinha Laranja Neon 38',
		'thumbnail' => Piki::url( 'images/colors/59.jpg', __FILE__ ),
	),
	's60' => array(
		'ID' => 's60',
		'label' => 'Romance Goiaba 36',
		'thumbnail' => Piki::url( 'images/colors/60.jpg', __FILE__ ),
	),
	's61' => array(
		'ID' => 's61',
		'label' => 'Azul Turquesa 12',
		'thumbnail' => Piki::url( 'images/colors/61.jpg', __FILE__ ),
	),
	's62' => array(
		'ID' => 's62',
		'label' => 'Soneca Branco 20',
		'thumbnail' => Piki::url( 'images/colors/62.jpg', __FILE__ ),
	),
	's63' => array(
		'ID' => 's63',
		'label' => 'Risca de Giz Rantelli Berinjela 17',
		'thumbnail' => Piki::url( 'images/colors/63.jpg', __FILE__ ),
	),
	's64' => array(
		'ID' => 's64',
		'label' => 'Risca de Giz Rantelli Carmim 06',
		'thumbnail' => Piki::url( 'images/colors/64.jpg', __FILE__ ),
	),
	's65' => array(
		'ID' => 's65',
		'label' => 'Chantal Prata 78',
		'thumbnail' => Piki::url( 'images/colors/65.jpg', __FILE__ ),
	),
	's66' => array(
		'ID' => 's66',
		'label' => 'Merlot Preto 27',
		'thumbnail' => Piki::url( 'images/colors/66.jpg', __FILE__ ),
	),
	's67' => array(
		'ID' => 's67',
		'label' => 'Fio Dental Copacabana Lavanda 34',
		'thumbnail' => Piki::url( 'images/colors/67.jpg', __FILE__ ),
	),
	's68' => array(
		'ID' => 's68',
		'label' => 'Fio Dental Copacabana Carmim 06',
		'thumbnail' => Piki::url( 'images/colors/68.jpg', __FILE__ ),
	),
	's69' => array(
		'ID' => 's69',
		'label' => 'Sutiã Luar Carmim 06',
		'thumbnail' => Piki::url( 'images/colors/69.jpg', __FILE__ ),
	),
	's70' => array(
		'ID' => 's70',
		'label' => 'Coleção Gemma e Camisola Soltinha Salmão 87',
		'thumbnail' => Piki::url( 'images/colors/70.jpg', __FILE__ ),
	),
	's71' => array(
		'ID' => 's71',
		'label' => 'Coleção Gemma e Camisola Soltinha Menta 33',
		'thumbnail' => Piki::url( 'images/colors/71.jpg', __FILE__ ),
	),
	's72' => array(
		'ID' => 's72',
		'label' => 'Cálice Bege Rosado 55',
		'thumbnail' => Piki::url( 'images/colors/72.jpg', __FILE__ ),
	),
	's73' => array(
		'ID' => 's73',
		'label' => 'Sonata Preto 27',
		'thumbnail' => Piki::url( 'images/colors/73.jpg', __FILE__ ),
	),
	's74' => array(
		'ID' => 's74',
		'label' => 'Cintilante Branco 20',
		'thumbnail' => Piki::url( 'images/colors/74.jpg', __FILE__ ),
	),
	's75' => array(
		'ID' => 's75',
		'label' => 'Cintilante Carmim 06',
		'thumbnail' => Piki::url( 'images/colors/75.jpg', __FILE__ ),
	),
	's76' => array(
		'ID' => 's76',
		'label' => 'Cintilante Preto 27',
		'thumbnail' => Piki::url( 'images/colors/76.jpg', __FILE__ ),
	),
	's77' => array(
		'ID' => 's77',
		'label' => 'Paquera Branco 20',
		'thumbnail' => Piki::url( 'images/colors/77.jpg', __FILE__ ),
	),
	's78' => array(
		'ID' => 's78',
		'label' => 'Paquera Pink 51',
		'thumbnail' => Piki::url( 'images/colors/78.jpg', __FILE__ ),
	),
	's79' => array(
		'ID' => 's79',
		'label' => 'Paquera Laranja 84',
		'thumbnail' => Piki::url( 'images/colors/79.jpg', __FILE__ ),
	),
	's80' => array(
		'ID' => 's80',
		'label' => 'Di Carla Púrpura 62',
		'thumbnail' => Piki::url( 'images/colors/80.jpg', __FILE__ ),
	),
	's81' => array(
		'ID' => 's81',
		'label' => 'Toque de Seda Jeans 94',
		'thumbnail' => Piki::url( 'images/colors/81.jpg', __FILE__ ),
	),
	's82' => array(
		'ID' => 's82',
		'label' => 'Relevo em Poás Salmão 87',
		'thumbnail' => Piki::url( 'images/colors/82.jpg', __FILE__ ),
	),
	's83' => array(
		'ID' => 's83',
		'label' => 'Tentadora Carmim 06',
		'thumbnail' => Piki::url( 'images/colors/83.jpg', __FILE__ ),
	),
	's84' => array(
		'ID' => 's84',
		'label' => 'Gradisca Marinho 15',
		'thumbnail' => Piki::url( 'images/colors/84.jpg', __FILE__ ),
	),
	's85' => array(
		'ID' => 's85',
		'label' => 'Noite Requinte Rosa Seco 47',
		'thumbnail' => Piki::url( 'images/colors/85.jpg', __FILE__ ),
	),
	's86' => array(
		'ID' => 's86',
		'label' => 'Velvette Fúcsia 93',
		'thumbnail' => Piki::url( 'images/colors/86.jpg', __FILE__ ),
	),
	's87' => array(
		'ID' => 's87',
		'label' => 'Kisslove Branco 20',
		'thumbnail' => Piki::url( 'images/colors/87.jpg', __FILE__ ),
	),
	's88' => array(
		'ID' => 's88',
		'label' => 'Goldy Carmim 06',
		'thumbnail' => Piki::url( 'images/colors/88.jpg', __FILE__ ),
	),
	's89' => array(
		'ID' => 's89',
		'label' => 'Cintilante Preto 27',
		'thumbnail' => Piki::url( 'images/colors/89.jpg', __FILE__ ),
	),
	's90' => array(
		'ID' => 's90',
		'label' => 'Cecile Menta 33',
		'thumbnail' => Piki::url( 'images/colors/90.jpg', __FILE__ ),
	),
	's91' => array(
		'ID' => 's91',
		'label' => 'Rivali Carmim 06',
		'thumbnail' => Piki::url( 'images/colors/91.jpg', __FILE__ ),
	),
	's92' => array(
		'ID' => 's92',
		'label' => 'Recreio Borboleta Menta 33',
		'thumbnail' => Piki::url( 'images/colors/92.jpg', __FILE__ ),
	),
	's93' => array(
		'ID' => 's93',
		'label' => 'Recreio Xadrez Salmão 87',
		'thumbnail' => Piki::url( 'images/colors/93.jpg', __FILE__ ),
	),
	's94' => array(
		'ID' => 's94',
		'label' => 'Recreio Corações Neve 09',
		'thumbnail' => Piki::url( 'images/colors/94.jpg', __FILE__ ),
	),
	's95' => array(
		'ID' => 's95',
		'label' => 'Apricot Marinho 15',
		'thumbnail' => Piki::url( 'images/colors/95.jpg', __FILE__ ),
	),
	's96' => array(
		'ID' => 's96',
		'label' => 'Super Star Branco 20',
		'thumbnail' => Piki::url( 'images/colors/96.jpg', __FILE__ ),
	),
	's97' => array(
		'ID' => 's97',
		'label' => 'Tarantela Branco 20',
		'thumbnail' => Piki::url( 'images/colors/97.jpg', __FILE__ ),
	),
	's98' => array(
		'ID' => 's98',
		'label' => 'Variance Ultraleve Azul Capri 01',
		'thumbnail' => Piki::url( 'images/colors/98.jpg', __FILE__ ),
	),
	's99' => array(
		'ID' => 's99',
		'label' => 'Variance Ultraleve Coral 42',
		'thumbnail' => Piki::url( 'images/colors/99.jpg', __FILE__ ),
	),
	's100' => array(
		'ID' => 's100',
		'label' => 'Variance Ultraleve Uva 82',
		'thumbnail' => Piki::url( 'images/colors/100.jpg', __FILE__ ),
	),
	's101' => array(
		'ID' => 's101',
		'label' => 'Cueca Zeus Cinza 65',
		'thumbnail' => Piki::url( 'images/colors/101.jpg', __FILE__ ),
	),
	's102' => array(
		'ID' => 's102',
		'label' => 'Cueca Zeus Marinho 16',
		'thumbnail' => Piki::url( 'images/colors/102.jpg', __FILE__ ),
	),
	's103' => array(
		'ID' => 's103',
		'label' => 'Cueca Zeus Preto 27',
		'thumbnail' => Piki::url( 'images/colors/103.jpg', __FILE__ ),
	),
	's104' => array(
		'ID' => 's104',
		'label' => 'Pijama Masculino Marinho 15',
		'thumbnail' => Piki::url( 'images/colors/104.jpg', __FILE__ ),
	),
	's105' => array(
		'ID' => 's105',
		'label' => 'Pijama Masculino Cinza Mescla 64',
		'thumbnail' => Piki::url( 'images/colors/105.jpg', __FILE__ ),
	),
	's106' => array(
		'ID' => 's106',
		'label' => 'Preto 27',
		'thumbnail' => Piki::url( 'images/colors/106.jpg', __FILE__ ),
	),
	's107' => array(
		'ID' => 's107',
		'label' => 'Branco 20',
		'thumbnail' => Piki::url( 'images/colors/107.jpg', __FILE__ ),
	),
	's108' => array(
		'ID' => 's108',
		'label' => 'Grafite 85',
		'thumbnail' => Piki::url( 'images/colors/108.jpg', __FILE__ ),
	),
	's109' => array(
		'ID' => 's109',
		'label' => 'Chumbo 91',
		'thumbnail' => Piki::url( 'images/colors/109.jpg', __FILE__ ),
	),
	's110' => array(
		'ID' => 's110',
		'label' => 'Cinza Mesclado 64',
		'thumbnail' => Piki::url( 'images/colors/110.jpg', __FILE__ ),
	),
	's111' => array(
		'ID' => 's111',
		'label' => 'Cinza 65',
		'thumbnail' => Piki::url( 'images/colors/111.jpg', __FILE__ ),
	),
	's112' => array(
		'ID' => 's112',
		'label' => 'Prata 78',
		'thumbnail' => Piki::url( 'images/colors/112.jpg', __FILE__ ),
	),
	's113' => array(
		'ID' => 's113',
		'label' => 'Cinza Mescla 65',
		'thumbnail' => Piki::url( 'images/colors/113.jpg', __FILE__ ),
	),
	's114' => array(
		'ID' => 's114',
		'label' => 'Marinho 15',
		'thumbnail' => Piki::url( 'images/colors/114.jpg', __FILE__ ),
	),
	's115' => array(
		'ID' => 's115',
		'label' => 'Azul Marinho 16',
		'thumbnail' => Piki::url( 'images/colors/115.jpg', __FILE__ ),
	),
	's116' => array(
		'ID' => 's116',
		'label' => 'Carbono 68',
		'thumbnail' => Piki::url( 'images/colors/116.jpg', __FILE__ ),
	),
	's117' => array(
		'ID' => 's117',
		'label' => 'Azul Cobalto 32',
		'thumbnail' => Piki::url( 'images/colors/117.jpg', __FILE__ ),
	),
	's118' => array(
		'ID' => 's118',
		'label' => 'Azul Petróleo 69',
		'thumbnail' => Piki::url( 'images/colors/118.jpg', __FILE__ ),
	),
	's119' => array(
		'ID' => 's119',
		'label' => 'Azul Klein 39',
		'thumbnail' => Piki::url( 'images/colors/119.jpg', __FILE__ ),
	),
	's120' => array(
		'ID' => 's120',
		'label' => 'Azul Royal 50',
		'thumbnail' => Piki::url( 'images/colors/120.jpg', __FILE__ ),
	),
	's121' => array(
		'ID' => 's121',
		'label' => 'Azul Caribe 07',
		'thumbnail' => Piki::url( 'images/colors/121.jpg', __FILE__ ),
	),
	's121b' => array(
		'ID' => 's121b',
		'label' => 'Azul Laguna 43',
		'thumbnail' => Piki::url( 'images/colors/121b.jpg', __FILE__ ),
	),
	's122' => array(
		'ID' => 's122',
		'label' => 'Jeans 94',
		'thumbnail' => Piki::url( 'images/colors/122.jpg', __FILE__ ),
	),
	's123' => array(
		'ID' => 's123',
		'label' => 'Azul Turquesa 12',
		'thumbnail' => Piki::url( 'images/colors/123.jpg', __FILE__ ),
	),
	's124' => array(
		'ID' => 's124',
		'label' => 'Azul Pavão 95',
		'thumbnail' => Piki::url( 'images/colors/124.jpg', __FILE__ ),
	),
	's125' => array(
		'ID' => 's125',
		'label' => 'Azul Pacífico 13',
		'thumbnail' => Piki::url( 'images/colors/125.jpg', __FILE__ ),
	),
	's126' => array(
		'ID' => 's126',
		'label' => 'Azul Capri 01',
		'thumbnail' => Piki::url( 'images/colors/126.jpg', __FILE__ ),
	),
	's127' => array(
		'ID' => 's127',
		'label' => 'Verde Musgo 98',
		'thumbnail' => Piki::url( 'images/colors/127.jpg', __FILE__ ),
	),
	's128' => array(
		'ID' => 's128',
		'label' => 'Oliva 35',
		'thumbnail' => Piki::url( 'images/colors/128.jpg', __FILE__ ),
	),
	's129' => array(
		'ID' => 's129',
		'label' => 'Verde Bandeira 29',
		'thumbnail' => Piki::url( 'images/colors/129.jpg', __FILE__ ),
	),
	's130' => array(
		'ID' => 's130',
		'label' => 'Lima Neon 19',
		'thumbnail' => Piki::url( 'images/colors/130.jpg', __FILE__ ),
	),
	's131' => array(
		'ID' => 's131',
		'label' => 'Pistache 08',
		'thumbnail' => Piki::url( 'images/colors/131.jpg', __FILE__ ),
	),
	's132' => array(
		'ID' => 's132',
		'label' => 'Verde Água 74',
		'thumbnail' => Piki::url( 'images/colors/132.jpg', __FILE__ ),
	),
	's133' => array(
		'ID' => 's133',
		'label' => 'Jade 52',
		'thumbnail' => Piki::url( 'images/colors/133.jpg', __FILE__ ),
	),
	's134' => array(
		'ID' => 's134',
		'label' => 'Verde Pera 92',
		'thumbnail' => Piki::url( 'images/colors/134.jpg', __FILE__ ),
	),
	's135' => array(
		'ID' => 's135',
		'label' => 'Rosa Neon 52',
		'thumbnail' => Piki::url( 'images/colors/135.jpg', __FILE__ ),
	),
	's136' => array(
		'ID' => 's136',
		'label' => 'Fúcsia 93',
		'thumbnail' => Piki::url( 'images/colors/136.jpg', __FILE__ ),
	),
	's137' => array(
		'ID' => 's137',
		'label' => 'Goiaba 36',
		'thumbnail' => Piki::url( 'images/colors/137.jpg', __FILE__ ),
	),
	's138' => array(
		'ID' => 's138',
		'label' => 'Rosa Chiclete 04',
		'thumbnail' => Piki::url( 'images/colors/138.jpg', __FILE__ ),
	),
	's139' => array(
		'ID' => 's139',
		'label' => 'Pink 51',
		'thumbnail' => Piki::url( 'images/colors/139.jpg', __FILE__ ),
	),
	's140' => array(
		'ID' => 's140',
		'label' => 'Rosa 30',
		'thumbnail' => Piki::url( 'images/colors/140.jpg', __FILE__ ),
	),
	's141' => array(
		'ID' => 's141',
		'label' => 'Rosa Seco 47',
		'thumbnail' => Piki::url( 'images/colors/141.jpg', __FILE__ ),
	),
	's142' => array(
		'ID' => 's142',
		'label' => 'Rosa Verano 03',
		'thumbnail' => Piki::url( 'images/colors/142.jpg', __FILE__ ),
	),
	's143' => array(
		'ID' => 's143',
		'label' => 'Beringela 17',
		'thumbnail' => Piki::url( 'images/colors/143.jpg', __FILE__ ),
	),
	's144' => array(
		'ID' => 's144',
		'label' => 'Púrpura 62',
		'thumbnail' => Piki::url( 'images/colors/144.jpg', __FILE__ ),
	),
	's145' => array(
		'ID' => 's145',
		'label' => 'Lilás Malva 60',
		'thumbnail' => Piki::url( 'images/colors/145.jpg', __FILE__ ),
	),
	's146' => array(
		'ID' => 's146',
		'label' => 'Ameixa 37',
		'thumbnail' => Piki::url( 'images/colors/146.jpg', __FILE__ ),
	),
	's147' => array(
		'ID' => 's147',
		'label' => 'Lavanda 34',
		'thumbnail' => Piki::url( 'images/colors/147.jpg', __FILE__ ),
	),
	's148' => array(
		'ID' => 's148',
		'label' => 'Lilás 11',
		'thumbnail' => Piki::url( 'images/colors/148.jpg', __FILE__ ),
	),
	's149' => array(
		'ID' => 's149',
		'label' => 'Lilás Místico 44',
		'thumbnail' => Piki::url( 'images/colors/149.jpg', __FILE__ ),
	),
	's150' => array(
		'ID' => 's150',
		'label' => 'Vermelho 41',
		'thumbnail' => Piki::url( 'images/colors/150.jpg', __FILE__ ),
	),
	's151' => array(
		'ID' => 's151',
		'label' => 'Bordô 24',
		'thumbnail' => Piki::url( 'images/colors/151.jpg', __FILE__ ),
	),
	's152' => array(
		'ID' => 's152',
		'label' => 'Cereja 90',
		'thumbnail' => Piki::url( 'images/colors/152.jpg', __FILE__ ),
	),
	's153' => array(
		'ID' => 's153',
		'label' => 'Vinho 21',
		'thumbnail' => Piki::url( 'images/colors/153.jpg', __FILE__ ),
	),
	's154' => array(
		'ID' => 's154',
		'label' => 'Carmim 06',
		'thumbnail' => Piki::url( 'images/colors/154.jpg', __FILE__ ),
	),
	's154b' => array(
		'ID' => 's154b',
		'label' => 'Orquídea 88',
		'thumbnail' => Piki::url( 'images/colors/154b.jpg', __FILE__ ),
	),
	's155' => array(
		'ID' => 's155',
		'label' => 'Uva 82',
		'thumbnail' => Piki::url( 'images/colors/155.jpg', __FILE__ ),
	),
	's156' => array(
		'ID' => 's156',
		'label' => 'Coral 42',
		'thumbnail' => Piki::url( 'images/colors/156.jpg', __FILE__ ),
	),
	's157' => array(
		'ID' => 's157',
		'label' => 'Laranja Neon 38',
		'thumbnail' => Piki::url( 'images/colors/157.jpg', __FILE__ ),
	),
	's158' => array(
		'ID' => 's158',
		'label' => 'Corali 83',
		'thumbnail' => Piki::url( 'images/colors/158.jpg', __FILE__ ),
	),
	's159' => array(
		'ID' => 's159',
		'label' => 'Laranja 84',
		'thumbnail' => Piki::url( 'images/colors/159.jpg', __FILE__ ),
	),
	's160' => array(
		'ID' => 's160',
		'label' => 'Café 76',
		'thumbnail' => Piki::url( 'images/colors/160.jpg', __FILE__ ),
	),
	's161' => array(
		'ID' => 's161',
		'label' => 'Cappuccino 40',
		'thumbnail' => Piki::url( 'images/colors/161.jpg', __FILE__ ),
	),
	's162' => array(
		'ID' => 's162',
		'label' => 'Nude 14',
		'thumbnail' => Piki::url( 'images/colors/162.jpg', __FILE__ ),
	),
	's163' => array(
		'ID' => 's163',
		'label' => 'Bege-rosado 55',
		'thumbnail' => Piki::url( 'images/colors/163.jpg', __FILE__ ),
	),
	's164' => array(
		'ID' => 's164',
		'label' => 'Cáqui 97',
		'thumbnail' => Piki::url( 'images/colors/164.jpg', __FILE__ ),
	),
	's165' => array(
		'ID' => 's165',
		'label' => 'Champanhe 59',
		'thumbnail' => Piki::url( 'images/colors/165.jpg', __FILE__ ),
	),
	's166' => array(
		'ID' => 's166',
		'label' => 'Ouro Velho 66',
		'thumbnail' => Piki::url( 'images/colors/166.jpg', __FILE__ ),
	),
	's167' => array(
		'ID' => 's167',
		'label' => 'Amarelo Ouro 63',
		'thumbnail' => Piki::url( 'images/colors/167.jpg', __FILE__ ),
	),
	's168' => array(
		'ID' => 's168',
		'label' => 'Amarelo Solar 77',
		'thumbnail' => Piki::url( 'images/colors/168.jpg', __FILE__ ),
	),
	's169' => array(
		'ID' => 's169',
		'label' => 'Amarelo Verano 05',
		'thumbnail' => Piki::url( 'images/colors/169.jpg', __FILE__ ),
	),
	's170' => array(
		'ID' => 's170',
		'label' => 'Meias Neve 09',
		'thumbnail' => Piki::url( 'images/colors/170.jpg', __FILE__ ),
	),
	's171' => array(
		'ID' => 's171',
		'label' => 'Meias Pérola 14',
		'thumbnail' => Piki::url( 'images/colors/171.jpg', __FILE__ ),
	),
	's172' => array(
		'ID' => 's172',
		'label' => 'Meias ASNl 73',
		'thumbnail' => Piki::url( 'images/colors/172.jpg', __FILE__ ),
	),
	's173' => array(
		'ID' => 's173',
		'label' => 'Meias Café 80',
		'thumbnail' => Piki::url( 'images/colors/173.jpg', __FILE__ ),
	),
	's174' => array(
		'ID' => 's174',
		'label' => 'Meias Castanho 32',
		'thumbnail' => Piki::url( 'images/colors/174.jpg', __FILE__ ),
	),
	's175' => array(
		'ID' => 's175',
		'label' => 'Meias Tabaco 49',
		'thumbnail' => Piki::url( 'images/colors/175.jpg', __FILE__ ),
	),
	's176' => array(
		'ID' => 's176',
		'label' => 'Meias Chocolate 22',
		'thumbnail' => Piki::url( 'images/colors/176.jpg', __FILE__ ),
	),
	's177' => array(
		'ID' => 's177',
		'label' => 'Meias Púrpura 62',
		'thumbnail' => Piki::url( 'images/colors/177.jpg', __FILE__ ),
	),
	's178' => array(
		'ID' => 's178',
		'label' => 'Meias Vermelho 41',
		'thumbnail' => Piki::url( 'images/colors/178.jpg', __FILE__ ),
	),
	's179' => array(
		'ID' => 's179',
		'label' => 'Meias Cinza Mescla 64',
		'thumbnail' => Piki::url( 'images/colors/179.jpg', __FILE__ ),
	),
	's180' => array(
		'ID' => 's180',
		'label' => 'Meias Preto Noite 54',
		'thumbnail' => Piki::url( 'images/colors/180.jpg', __FILE__ ),
	),
	's181' => array(
		'ID' => 's181',
		'label' => 'Leggings Preto Noite 54',
		'thumbnail' => Piki::url( 'images/colors/181.jpg', __FILE__ ),
	),
	's182' => array(
		'ID' => 's182',
		'label' => 'Leggings Grafite 85',
		'thumbnail' => Piki::url( 'images/colors/182.jpg', __FILE__ ),
	),
);